export { default as Navbar } from './Navbar'
export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Gallery } from './Gallery'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
